/**
 * Outreach / contact entities.
 *
 * Outreach briefs are NOT spam templates. They are structured briefs that:
 *  - state the verified reason for outreach
 *  - cite evidence
 *  - distinguish fact vs inference vs unknown
 *  - include do-not-contact flags
 */
import { VerificationStatus } from "./verification.js";
import { RiskFlag } from "./risk.js";

export interface ContactCandidate {
  id: string;
  /** Origin page or domain. */
  originRef: string;
  /** Public-facing name (only if observed). */
  name?: string;
  /** Role/title (only if observed). */
  role?: string;
  /** Public email (only if observed on a public page or supplied by CRM). */
  email?: string;
  /** Public contact form URL (only if observed). */
  contactFormUrl?: string;
  /** Social handles (only if observed). */
  socials?: { platform: string; handle: string }[];
  /** Provenance: how this contact was discovered. */
  provenance: "page_contact_info" | "author_profile" | "org_contact_page" | "crm_export" | "manual" | "adapter";
  /** Verification state. */
  verification: VerificationStatus;
  /** Whether this contact is on a do-not-contact list. */
  doNotContact: boolean;
  /** Reason for DNC, if any. */
  doNotContactReason?: string;
  /** Evidence ids. */
  evidenceIds: string[];
  /** Risk flags. */
  riskFlags: RiskFlag[];
}

export interface OutreachProspect {
  id: string;
  siteProfileId: string;
  opportunityId: string;
  contactId?: string;
  /** Verification state of the prospect. */
  verification: VerificationStatus;
  /** Personalization confidence. */
  personalizationConfidence: number;
  /** Risk flags. */
  riskFlags: RiskFlag[];
  /** Brief, generated by the outreach personalization engine. */
  brief: OutreachBrief;
  /** Created at. */
  createdAt: number;
}

export interface OutreachBrief {
  /** Factual, evidence-backed reason for outreach. */
  outreachReason: string;
  /** Personalized context (clearly marked as inferred or observed). */
  personalizedContext: {
    value: string;
    basis: "observed" | "inferred" | "unknown";
  };
  /** Target asset on our property. */
  targetAsset: {
    pageId?: string;
    url?: string;
    title?: string;
    rationale: string;
  };
  /** Evidence references. */
  evidenceIds: string[];
  /** Suggested subject-line concepts (not final copy). */
  suggestedSubjectConcepts: string[];
  /** Concise draft variants (clearly labeled as drafts). */
  draftVariants: {
    label: string;
    body: string;
  }[];
  /** Follow-up strategy. */
  followUpStrategy: string;
  /** Do-not-contact flags. */
  doNotContact: boolean;
  /** Risk flags carried forward. */
  riskFlags: RiskFlag[];
  /** Distinguishing marks for fact vs inference. */
  factInferenceUnknown: {
    facts: string[];
    inferences: string[];
    unknowns: string[];
  };
}
